[setting]
port = 8088

[database]
Host = "127.0.0.1"
User = "root"
Password = "my-secret-pw"
Name = "academic"
Port = 33061
Timezone = "UTC"
MaxIdleConns = 10
MaxOpenConns = 100
ConnMaxLifetime = 3600 # seconds

[log]
console_level = "debug"
stacktrace_level = "panic"

[redis]
address = "127.0.0.1:32768"
password = "redispw"

[jaeger]
name = "dms-api"
endpoint = "http://127.0.0.1:14268/api/traces"
udp_host = "localhost"
udp_port = "5775"

[simulator]
name = "child-service"
port = 9088

[kafka]
version = "3.4.0"
brokers = ["localhost:29092"]
topic = "users-notify"
group_id = "tracing-example-group-id-dev"
