@port = 8080
@host = localhost:{{port}}
@token = Authorization: Bearer 1

# Read
GET http://{{host}}/v1/class/1 HTTP/1.1
{{token}}
###

GET http://{{host}}/v1/user/1 HTTP/1.1
{{token}}
###

# Create
POST http://{{host}}/v1/user HTTP/1.1
Content-Type: application/x-www-form-urlencoded
{{token}}
###

# Update
PUT http://{{host}}/v1/user/22 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
{{token}}
